version: '3'
services:
  app:
    build: ./
    command: ./startup.sh serve
    volumes:
      - ./:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle
    working_dir: /srv/jekyll
    ports:
      - "4000:4000"
      - "35729:35729"